<a href="https://colab.research.google.com/github/Nilesh-jha8877/AIML/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time

In [ ]:
arr=np.array({1,2,3,4,5})
print(arr,type(arr))

{1, 2, 3, 4, 5} <class 'numpy.ndarray'>


In [ ]:
#Execution Time Comparision
#python array
size=10_000_00
python_list=list(range(size))
start=time.time()
list_squared=[x**2 for x in python_list]
end=time.time()
print("python list time :",end-start,"seconds")

#Numpy arays
numpy_array=np.array(python_list)
start=time.time()
array_squared=numpy_array**2
end=time.time()
print("Numpy array time ",end-start,"seconds")


python list time : 0.0973963737487793 seconds
Numpy array time  0.004769802093505859 seconds


In [ ]:
#Memory Usage Comparison
import sys
print("python list size",sys.getsizeof(python_list)*len(python_list))
print("Numpy array size",numpy_array.nbytes)

python list size 8000056000000
Numpy array size 8000000


In [ ]:
#Creating Numpy Arrays_from lists
arr=np.array([1,2,3,4])
print(arr,type(arr))
arr2=np.array([1,2,3,4,"prime"])
print(arr2,type(arr2))
arr3=np.array([[1,2,3,4],[4,5,6,7]])
print(arr3,arr3.shape)

[1 2 3 4] <class 'numpy.ndarray'>
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'>
[[1 2 3 4]
 [4 5 6 7]] (2, 4)


In [ ]:
#Creating Numpy Arrays_from Scarth
arr1=np.zeros((3,4))
print(arr1,arr1.shape)
arr2=np.ones((3,3))
print(arr2,arr2.shape)
arr3=np.full((2,3),5)
print(arr3,arr3.shape)
arr4=np.eye((3))
print(arr4,arr4.shape)
arr5=np.arange(1,20,2)
print(arr5)
arr6=np.linspace(0,10,5)
print(arr6)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (3, 4)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[5 5 5]
 [5 5 5]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  3  5  7  9 11 13 15 17 19]
[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#useful Attributes
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

#specify dtype at creation
str_arr=np.array([1,2,3],dtype="U")
print(str_arr,str_arr.dtype)
float_arr=np.array([1,2,3],dtype="float32")
print(str_arr,float_arr.dtype)


(4, 3)
12
2
int64
8
['1' '2' '3'] <U1
['1' '2' '3'] float32


In [ ]:
#Reshaping
arr=np.array([1,2,3,4,5,6])
print(arr.shape)
reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)
flattened=reshaped.flatten()
print(flattened,flattened.shape)

(6,)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [ ]:
#Indexing for 1d array
arr=np.array([1,2,3,4,5])
print(arr[0])
#indexing of 2d array
arr=np.array([[1,2,3,],[4,5,6],[7,8,9],[10,11,12]])
print(arr[0][1])
print(arr[1][2])
#Fancy Indexing
arr=np.array([1,2,3,4,5])
idx=[0,1,4]
print(arr[idx])
#boolean indexing
print(arr[arr>2])

1
2
6
[1 2 5]
[3 4 5]


In [ ]:
#slicing
arr=np.array([1,2,3,4,5,6,7])
print(arr[2:6])
print(arr[:6])
print(arr[1:])
print(arr[::2])

[3 4 5 6]
[1 2 3 4 5 6]
[2 3 4 5 6 7]
[1 3 5 7]


In [ ]:
#Sliced list is a copy
py_list=[1,2,3,4,5]
copy_list=py_list[1:4]
copy_list[1]=333
print(copy_list)
print(py_list)
#Sliced array is a view
np_arr=np.array([1,2,3,4,5])
view_arr=np_arr[1:4]
view_arr[1]=333
print(view_arr)
print(np_arr)

#creating a Copy for array
copy_arr=np_arr[1:4].copy()
copy_arr[2]=444
print(copy_arr)
print(np_arr)

[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
[  2 333 444]
[  1   2 333   4   5]


In [ ]:
#multidimensional Array
arr1D=np.array([1,2,3])
print(arr1D.ndim)
arr2D=np.array([[1,2,3],
               [4,5,6]]
               )
print(arr2D.ndim)
arr3D=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr3D.ndim)


1
2
3


In [ ]:
#operation along axes
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr2D))
sum_of_columns=np.sum(arr2D,axis=0)
print(sum_of_columns)
sum_of_columns=np.sum(arr2D,axis=1)
print(sum_of_columns)
print(arr2D[0:3,1:3])

45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]
 [8 9]]


In [ ]:
#operation on 3d arrays
arr3D=np.array([[[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]]])
print(arr3D,arr3D.shape)
print(arr3D[0][1][1])
print(arr3D[0][2][1])
print(arr3D[:,:,0])
print(arr3D[:,0,:])
arr3D[:,0,:]=99
print(arr3D)



[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]] (1, 6, 2)
4
6
[[ 1  3  5  7  9 11]]
[[1 2]]
[[[99 99]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
#common Data Types
arr=np.array([1,2,3,4,5])
arr2=np.array([1.0,2.0,3.0,4.0])
arr3=np.array(["hello","world","primr","ai/ml"])
print(arr.dtype)
print(arr2.dtype)
print(arr3.dtype)

#complex Numbers
arr1=np.array([2+3j])
arr1=np.array([5+8j])
print(arr1,arr1.dtype)
print(arr1+arr2)
print(arr2-arr1)

#objects
arr=np.array(["Hello",{1,2,3},3.14])
print(arr,arr.dtype)

int64
float64
<U5
[5.+8.j] complex128
[6.+8.j 7.+8.j 8.+8.j 9.+8.j]
[-4.-8.j -3.-8.j -2.-8.j -1.-8.j]
[{1, 2, 3} 3.14] object


In [ ]:
#Changing the data type
# new_arr=arr.astype("float64")
# print(new_arr,new_arr.dtype)
new_arr=np.array([1,2,3,4,5], dtype="float64")
print(new_arr,new_arr.dtype)

[1. 2. 3. 4. 5.] float64


In [ ]:
#vectorization
arr=np.array([1,2,3,4,5])
sq_arr=arr**2
print(sq_arr)
arr2=np.array([5,6,7,8,9])
print(arr+arr2)

[ 1  4  9 16 25]
[ 6  8 10 12 14]


In [ ]:
#broadcasting
arr_mul10=arr*10
print(arr_mul10)
arr1D=np.array([1,2,3])
arr2D=np.array([[1,2,3],[4,5,6]])
print(arr1D+arr2D)

[10 20 30 40 50]
[[2 4 6]
 [5 7 9]]


In [ ]:
#Standard vector Normalization
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_dev=np.std(arr)
normalized_arr=(arr-mean)/std_dev
print(normalized_arr)
#Column wise Normalization
arr=np.array([[1,2],[3,4],[5,6]])
mean=np.mean(arr,axis=0)
std_dev=np.std(arr,axis=0)
print(arr-mean/std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
[[-0.83711731 -0.44948974]
 [ 1.16288269  1.55051026]
 [ 3.16288269  3.55051026]]


In [ ]:
#Mathematical operation
arr=np.array([1,2,3,4,5,6,7,8])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.max(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

#power function
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

#log and exponential functions
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

#Rounding Funtions
print(np.round(2.678))
print(np.floor(2.678))
print(np.ceil(2.678))
print(np.trunc(2.678))

36
40320
1
0
8
7
4.5
4.5
2.29128784747792
5.25
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
3.0
2.0
3.0
2.0


In [ ]:
#miscallenous Functions
arr=np.array([1,2,-5,3,8,-4,2,5])
print(np.abs(arr))
print(np.short(arr))
print(np.unique(arr))

[1 2 5 3 8 4 2 5]
[ 1  2 -5  3  8 -4  2  5]
[-5 -4  1  2  3  5  8]


In [ ]:
#Practice Question on Numpy
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
#2
arr1=np.zeros((3,3))
print(arr1)


#3
arr3=np.arange(10,50)
print(arr3)

#4
arr4=np.arange(1,10,2)
print(arr4)

#5
arr5=np.array([1,2,3,4,5,6])
print(arr5.shape,arr5.size,arr5.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[1 3 5 7 9]
(6,) 6 int64


In [ ]:
from IPython.core.application import ProfileAwareConfigLoader
#intermediate level question
arr2D=np.array([[1,2,3,4,5],
 [6,7,8,9,10]])
print(arr2D[1])

#2
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[2:5])

#3
#print(arr[a])


#4
arr1=np.array([4,5,6,7,8])
arr2=np.array([6,7,8,9,10])
print(arr1+arr2)

#5
mu_by2=arr1*2
print(mu_by2)

[ 6  7  8  9 10]
[3 4 5]
[10 12 14 16 18]
[ 8 10 12 14 16]


In [ ]:
#important question
arr2D=np.array([[1,2,3],[4,5,6],[6,7,8]])
print(np.sum(arr2D,axis=0))
print(np.sum(arr2D,axis=1))
print(np.max(arr2D,axis=0))
print(np.max(arr2D,axis=1))
print(np.mean(arr2D,axis=0))
print(np.mean(arr2D,axis=1))


[11 14 17]
[ 6 15 21]
[6 7 8]
[3 6 8]
[3.66666667 4.66666667 5.66666667]
[2. 5. 7.]


In [ ]:
#Advance Practice question
